"""Export the static browser inputs from the same evidence used by Python."""
import json
import re
import pandas as pd
from config import ROOT, assumptions, read_dataset, write_json

def records(frame):
    return json.loads(frame.to_json(orient='records', double_precision=12))

def export_interactive():
    a = assumptions()
    electricity = read_dataset('indonesia_electricity')
    latest = electricity[electricity.year.eq(a['national_denominator']['year'])].iloc[0]
    projects = read_dataset('datacenter_projects')
    one = read_dataset('additional_1gw').query("case == 'base'").iloc[0]
    current = read_dataset('current_baseline_estimates').query("case == 'base'").iloc[0]
    inventory = read_dataset('documented_inventory_estimates').iloc[0]
    values = {
        'base_facility_twh': f'{one.facility_electricity_twh:,.2f}',
        'base_load_pct': f'{one.utilization * 100:.0f}', 'base_pue': f'{one.pue:.2f}',
        'baseline_mw': f"{a['baseline']['it_capacity_mw']:,.0f}",
        'current_twh': f'{current.facility_electricity_twh:,.2f}',
        'inventory_mw': f'{inventory.it_capacity_mw:,.1f}',
        'electricity_cost_tn': f'{one.electricity_cost_rp / 1e12:,.2f}',
        'electricity_tariff': f"{a['tariffs']['electricity_rp_per_kwh']:,.2f}",
        'average_load_gw': f'{one.average_facility_load_mw / 1000:.2f}',
        'full_load_gw': f'{one.full_it_load_facility_mw / 1000:.2f}',
        'national_share_pct': f'{one.share_national_consumption_pct:.2f}',
        'national_twh': f'{latest.electricity_consumption_twh:,.3f}',
        'base_wue': f'{one.wue_l_per_kwh:.2f}',
        'water_million_m3': f'{one.water_m3_per_year / 1e6:,.3f}',
        'water_tariff': f"{a['tariffs']['water_rp_per_m3']:,.0f}",
        'water_cost_bn': f'{one.water_cost_rp / 1e9:,.2f}',
    }
    newsletter = []
    copy = (ROOT / 'docs/newsletter_copy.md').read_text(encoding='utf-8')
    for section in re.split(r'^## ', copy, flags=re.MULTILINE)[1:]:
        title, body = section.split('\n', 1)
        body = re.sub(r'\{\{([a-z_][a-z_0-9]*)\}\}', lambda m: values[m.group(1)], body)
        if '{{' in body or '}}' in body:
            raise ValueError(f'Unresolved numerical placeholder in newsletter section: {title}')
        newsletter.append({'title': title.strip(), 'paragraphs': body.strip().split('\n\n')})
    # The region is a reading aid based on the disclosed city, not a site geocode.
    metro = {'Jakarta','Greater Jakarta','Cibitung','Cikarang','Bekasi','Bintaro',
             'South Tangerang','Serpong','Sentul','Jatiluhur','Karawang','Bandung'}
    projects['map_region'] = projects.location.map(lambda x: 'Greater Jakarta & West Java' if x in metro else x)
    dataset = {
        'cutoff': a['research_cutoff'], 'hours': a['hours_per_year'],
        'newsletter': newsletter,
        'flow_svg': (ROOT / 'interactive/flow-design.svg').read_text(encoding='utf-8'),
        'reader_urls': {
            'ELEC004': 'https://www.cushmanwakefield.com/en/singapore/news/2026/03/apac-data-centre-development-pipeline-hits-record-in-2025',
            'ELEC006': 'https://www.cushmanwakefield.com/en/singapore/news/2026/08/apac-dc-h1-2026',
        },
        'scenarios': a['scenarios'], 'tariffs': a['tariffs'],
        'national': {'year': int(latest.year), 'consumption_twh': float(latest.electricity_consumption_twh),
                     'source_id': a['national_denominator']['source_id']},
        'baseline': a['baseline'],
        'projects': records(projects), 'outlook': records(read_dataset('outlook_2030_2032')),
        'current': records(read_dataset('current_baseline_estimates')),
        'capacity_fixtures': records(read_dataset('capacity_scenarios')),
        'sources': records(pd.read_csv(ROOT / 'sources.csv')),
        'map': json.loads((ROOT / 'data/raw/evidence/indonesia_geometry.json').read_text(encoding='utf-8')),
    }
    target = ROOT / 'interactive'
    target.mkdir(exist_ok=True)
    write_json(target / 'data.json', dataset)
    # Script data also permits opening index.html without a local HTTP server.
    payload = json.dumps(dataset, ensure_ascii=False, allow_nan=False, separators=(',', ':')).replace('</', '<\\/')
    (target / 'data.js').write_text('/* Generated by src/export_interactive.py. */\nwindow.IDN_RESEARCH = ' + payload + ';\n', encoding='utf-8')
    print('Exported static interactive research inputs.')
    return target / 'index.html'

if __name__ == '__main__':
    export_interactive()
